# Generated by Django 5.0 on 2023-12-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('price_start', models.CharField(blank=True, max_length=8)),
                ('image', models.CharField(max_length=100)),
                ('video_card', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=150)),
                ('memory', models.CharField(max_length=15)),
                ('resolutions_supported', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
