# Generated by Django 5.0 on 2024-01-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_imageproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProject',
        ),
    ]
